[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
mmtokens = { path = "../../common/mmtokens" }
# serde = { version = "1.0", default-features = false, features = ["alloc", "derive", "no_std"] }
